# Generated by Django 6.0.2 on 2026-02-26 21:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('PARTICULIER', 'Particulier (Travailleur & Petit Recruteur)'), ('ENTREPRISE', 'Entreprise')], default='PARTICULIER', max_length=20)),
                ('phone', models.CharField(help_text='Ex: 077... ou 066...', max_length=15, verbose_name='Numéro Mobile Money')),
                ('ville', models.CharField(default='Libreville', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('competences', models.CharField(blank=True, help_text='Séparez par des virgules (ex: Chauffeur, Rayonniste)', max_length=255)),
                ('nom_entreprise', models.CharField(blank=True, max_length=150)),
                ('niu', models.CharField(blank=True, max_length=50, verbose_name='Numéro NIU')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categorie', models.CharField(help_text='Ex: Manutention, Ménage, Informatique', max_length=50)),
                ('ville', models.CharField(default='Libreville', max_length=50)),
                ('quartier', models.CharField(blank=True, max_length=50)),
                ('prix', models.PositiveIntegerField(help_text='Montant en FCFA')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert (En attente de candidats)'), ('RESERVE', 'Réservé (Paiement bloqué sur la plateforme)'), ('TERMINE', 'Mission terminée (En attente de validation)'), ('CLOTURE', 'Clôturé (Travailleur payé)')], default='OUVERT', max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_missions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
