# Generated by Django 6.0.2 on 2026-02-26 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='categorie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='prix',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='statut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('RESERVE', 'Réservé (Paiement bloqué)'), ('TERMINE', 'Mission terminée'), ('CLOTURE', 'Clôturé (Payé)')], default='OUVERT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='competences',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Numéro Mobile Money'),
        ),
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.PositiveIntegerField(default=0)),
                ('solde_bloque', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('type_transaction', models.CharField(choices=[('DEPOT', 'Dépôt'), ('PAIEMENT', 'Paiement'), ('RECEPTION', 'Réception')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('accepte', models.BooleanField(default=False)),
                ('date_postulation', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='interim.mission')),
                ('travailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mission', 'travailleur')},
            },
        ),
    ]
