# Generated by Django 6.0.2 on 2026-02-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0002_alter_mission_categorie_alter_mission_prix_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidature',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='candidature',
            name='note_travailleur',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
