# Generated by Django 6.0.2 on 2026-02-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0003_alter_candidature_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experiences',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Expériences'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
    ]
