# Generated by Django 6.0.2 on 2026-02-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0004_user_experiences_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='date_publication',
            new_name='date_creation',
        ),
        migrations.AddField(
            model_name='mission',
            name='date_mission',
            field=models.DateField(blank=True, null=True, verbose_name='Jour de la mission'),
        ),
        migrations.AddField(
            model_name='mission',
            name='horaire',
            field=models.CharField(blank=True, help_text='Ex: De 08h à 17h', max_length=100),
        ),
    ]
