# Generated by Django 6.0.2 on 2026-02-26 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0005_rename_date_publication_mission_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='interim.mission'),
        ),
    ]
