# Generated by Django 6.0.2 on 2026-02-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0006_alter_candidature_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_expiration_premium',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
