# Generated by Django 6.0.2 on 2026-02-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0008_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='boost_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
    ]
