# Generated by Django 6.0.2 on 2026-02-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0009_mission_boost_expires_at_mission_is_boosted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_soumission_verif',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fichier_piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='identite/'),
        ),
        migrations.AddField(
            model_name='user',
            name='statut_verification',
            field=models.CharField(choices=[('NON_VERIFIE', 'Non vérifié'), ('EN_ATTENTE', 'En attente de validation'), ('VERIFIE', 'Profil Vérifié ✅'), ('REJETE', 'Pièce rejetée')], default='NON_VERIFIE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='type_piece_identite',
            field=models.CharField(blank=True, choices=[('CNI', 'Carte Nationale d’Identité'), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de Conduire'), ('CNAMGS', 'Carte CNAMGS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='categorie',
            field=models.CharField(choices=[('MAISON', '🏠 Maison (Ménage, Cuisine, Nounou)'), ('BRICOLAGE', '🛠️ Travaux (Plomberie, Électricité, Maçonnerie)'), ('TRANSPORT', '🚗 Transport (Livraison, Chauffeur, Déménagement)'), ('TECH', '💻 Informatique (Réparation PC, Design, Web)'), ('BEAUTE', '✨ Beauté (Coiffure, Maquillage, Massage)'), ('SERVICES', '💼 Services (Cours particuliers, Gardiennage, Secrétariat)'), ('AUTRE', '➕ Autre service')], default='MAISON', max_length=50),
        ),
    ]
