# Generated by Django 6.0.2 on 2026-02-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0011_mission_nombre_places_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='budget_travailleur',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
