# Generated by Django 6.0.2 on 2026-02-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0012_mission_budget_travailleur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='budget_travailleur',
        ),
        migrations.AlterField(
            model_name='mission',
            name='prix',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
