# Generated by Django 6.0.2 on 2026-02-28 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0013_remove_mission_budget_travailleur_alter_mission_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='travailleur_selectionne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_effectuees', to=settings.AUTH_USER_MODEL),
        ),
    ]
