# Generated by Django 6.0.2 on 2026-03-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0014_mission_travailleur_selectionne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
