# Generated by Django 6.0.2 on 2026-03-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0015_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
