# Generated by Django 6.0.4 on 2026-05-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interim', '0016_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='pays',
            field=models.CharField(choices=[('GA', 'Gabon 🇬🇦'), ('GN', 'Guinée 🇬🇳'), ('CI', "Côte d'Ivoire 🇨🇮")], default='GA', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='devise',
            field=models.CharField(choices=[('XAF', 'FCFA (XAF)'), ('GNF', 'FG (GNF)')], default='XAF', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='pays',
            field=models.CharField(choices=[('GA', 'Gabon 🇬🇦'), ('GN', 'Guinée 🇬🇳'), ('CI', "Côte d'Ivoire 🇨🇮")], default='GA', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Numéro de Téléphone'),
        ),
    ]
